version: 2.1

# Define orbs for Docker and other utilities
orbs:
  docker: circleci/docker@2.2.0

# Define jobs
jobs:
  # Job to build and test the Flask application
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      
      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            cd backend
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      
      # Run basic tests (you can expand this section)
      - run:
          name: Run tests
          command: |
            cd backend
            source venv/bin/activate
            # Add your test commands here
            # For example: python -m pytest tests/
            echo "No tests defined yet - add your test suite here"
            
      # Lint the code (optional)
      - run:
          name: Lint code
          command: |
            cd backend
            source venv/bin/activate
            pip install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  # Job to build Docker image
  build-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      
      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t flask-app:${CIRCLE_SHA1} .
            docker tag flask-app:${CIRCLE_SHA1} flask-app:latest
      
      # Save Docker image to workspace (optional, for deployment)
      - run:
          name: Save Docker image
          command: |
            mkdir -p /tmp/docker-images
            docker save flask-app:${CIRCLE_SHA1} -o /tmp/docker-images/flask-app.tar
      
      - persist_to_workspace:
          root: /tmp/docker-images
          paths:
            - flask-app.tar

  # Job to deploy (customize based on your deployment target)
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      
      - attach_workspace:
          at: /tmp/docker-images
      
      # Load Docker image
      - run:
          name: Load Docker image
          command: |
            docker load -i /tmp/docker-images/flask-app.tar
      
      # Deploy to Docker Hub (optional)
      - run:
          name: Deploy to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
              docker tag flask-app:${CIRCLE_SHA1} $DOCKER_USERNAME/flask-app:${CIRCLE_SHA1}
              docker tag flask-app:${CIRCLE_SHA1} $DOCKER_USERNAME/flask-app:latest
              docker push $DOCKER_USERNAME/flask-app:${CIRCLE_SHA1}
              docker push $DOCKER_USERNAME/flask-app:latest
            fi

# Define workflows
workflows:
  version: 2
  build-test-deploy:
    jobs:
      # Run build and test for all branches
      - build-and-test:
          filters:
            branches:
              only: /.*/
      
      # Build Docker image for all branches
      - build-docker:
          requires:
            - build-and-test
          filters:
            branches:
              only: /.*/
      
      # Deploy only on main branch
      - deploy:
          requires:
            - build-docker
          filters:
            branches:
              only: main
