version: 2.1

jobs:
  build_test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install pip dependencies
          command: |
            cd backend
            pip install -r requirements.txt

  build_docker_image:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t flask-app -t gunadeep2607/flask-app:latest .
            echo $DOCKER_PASSWORD | docker login -u gunadeep2607 --password-stdin
            docker push gunadeep2607/flask-app:latest

workflows:
  build_test:
    jobs:
      - build_test  
      - build_docker_image
